services:
  - type: web
    name: check-insurance-risk-backend-final
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///data.db
      - key: FRONTEND_ORIGIN
        value: "*"
